//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace WindowsFormsApplication1
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class class_routineEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new class_routineEntities object using the connection string found in the 'class_routineEntities' section of the application configuration file.
        /// </summary>
        public class_routineEntities() : base("name=class_routineEntities", "class_routineEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new class_routineEntities object.
        /// </summary>
        public class_routineEntities(string connectionString) : base(connectionString, "class_routineEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new class_routineEntities object.
        /// </summary>
        public class_routineEntities(EntityConnection connection) : base(connection, "class_routineEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<info> infoes
        {
            get
            {
                if ((_infoes == null))
                {
                    _infoes = base.CreateObjectSet<info>("infoes");
                }
                return _infoes;
            }
        }
        private ObjectSet<info> _infoes;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the infoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToinfoes(info info)
        {
            base.AddObject("infoes", info);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="class_routineModel", Name="info")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class info : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new info object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static info Createinfo(global::System.Int32 id)
        {
            info info = new info();
            info.ID = id;
            return info;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Department
        {
            get
            {
                return _Department;
            }
            set
            {
                OnDepartmentChanging(value);
                ReportPropertyChanging("Department");
                _Department = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Department");
                OnDepartmentChanged();
            }
        }
        private global::System.String _Department;
        partial void OnDepartmentChanging(global::System.String value);
        partial void OnDepartmentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Program
        {
            get
            {
                return _Program;
            }
            set
            {
                OnProgramChanging(value);
                ReportPropertyChanging("Program");
                _Program = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Program");
                OnProgramChanged();
            }
        }
        private global::System.String _Program;
        partial void OnProgramChanging(global::System.String value);
        partial void OnProgramChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Campus
        {
            get
            {
                return _Campus;
            }
            set
            {
                OnCampusChanging(value);
                ReportPropertyChanging("Campus");
                _Campus = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Campus");
                OnCampusChanged();
            }
        }
        private global::System.String _Campus;
        partial void OnCampusChanging(global::System.String value);
        partial void OnCampusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Section
        {
            get
            {
                return _Section;
            }
            set
            {
                OnSectionChanging(value);
                ReportPropertyChanging("Section");
                _Section = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Section");
                OnSectionChanged();
            }
        }
        private global::System.String _Section;
        partial void OnSectionChanging(global::System.String value);
        partial void OnSectionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Label
        {
            get
            {
                return _Label;
            }
            set
            {
                OnLabelChanging(value);
                ReportPropertyChanging("Label");
                _Label = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Label");
                OnLabelChanged();
            }
        }
        private global::System.String _Label;
        partial void OnLabelChanging(global::System.String value);
        partial void OnLabelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Term
        {
            get
            {
                return _Term;
            }
            set
            {
                OnTermChanging(value);
                ReportPropertyChanging("Term");
                _Term = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Term");
                OnTermChanged();
            }
        }
        private global::System.String _Term;
        partial void OnTermChanging(global::System.String value);
        partial void OnTermChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Course_Code
        {
            get
            {
                return _Course_Code;
            }
            set
            {
                OnCourse_CodeChanging(value);
                ReportPropertyChanging("Course_Code");
                _Course_Code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Course_Code");
                OnCourse_CodeChanged();
            }
        }
        private global::System.String _Course_Code;
        partial void OnCourse_CodeChanging(global::System.String value);
        partial void OnCourse_CodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Course_Title
        {
            get
            {
                return _Course_Title;
            }
            set
            {
                OnCourse_TitleChanging(value);
                ReportPropertyChanging("Course_Title");
                _Course_Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Course_Title");
                OnCourse_TitleChanged();
            }
        }
        private global::System.String _Course_Title;
        partial void OnCourse_TitleChanging(global::System.String value);
        partial void OnCourse_TitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Teacher_Initial
        {
            get
            {
                return _Teacher_Initial;
            }
            set
            {
                OnTeacher_InitialChanging(value);
                ReportPropertyChanging("Teacher_Initial");
                _Teacher_Initial = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Teacher_Initial");
                OnTeacher_InitialChanged();
            }
        }
        private global::System.String _Teacher_Initial;
        partial void OnTeacher_InitialChanging(global::System.String value);
        partial void OnTeacher_InitialChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Weekday
        {
            get
            {
                return _Weekday;
            }
            set
            {
                OnWeekdayChanging(value);
                ReportPropertyChanging("Weekday");
                _Weekday = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Weekday");
                OnWeekdayChanged();
            }
        }
        private global::System.String _Weekday;
        partial void OnWeekdayChanging(global::System.String value);
        partial void OnWeekdayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Starting_Time
        {
            get
            {
                return _Starting_Time;
            }
            set
            {
                OnStarting_TimeChanging(value);
                ReportPropertyChanging("Starting_Time");
                _Starting_Time = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Starting_Time");
                OnStarting_TimeChanged();
            }
        }
        private global::System.String _Starting_Time;
        partial void OnStarting_TimeChanging(global::System.String value);
        partial void OnStarting_TimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ending_Time
        {
            get
            {
                return _Ending_Time;
            }
            set
            {
                OnEnding_TimeChanging(value);
                ReportPropertyChanging("Ending_Time");
                _Ending_Time = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ending_Time");
                OnEnding_TimeChanged();
            }
        }
        private global::System.String _Ending_Time;
        partial void OnEnding_TimeChanging(global::System.String value);
        partial void OnEnding_TimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Room
        {
            get
            {
                return _Room;
            }
            set
            {
                OnRoomChanging(value);
                ReportPropertyChanging("Room");
                _Room = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Room");
                OnRoomChanged();
            }
        }
        private global::System.String _Room;
        partial void OnRoomChanging(global::System.String value);
        partial void OnRoomChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Semester
        {
            get
            {
                return _Semester;
            }
            set
            {
                OnSemesterChanging(value);
                ReportPropertyChanging("Semester");
                _Semester = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Semester");
                OnSemesterChanged();
            }
        }
        private global::System.String _Semester;
        partial void OnSemesterChanging(global::System.String value);
        partial void OnSemesterChanged();

        #endregion

    
    }

    #endregion

    
}
